"""empty message

Revision ID: 02b6645c29fd
Revises: bbe75b803d68
Create Date: 2019-04-23 22:37:08.025568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b6645c29fd'
down_revision = 'bbe75b803d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carsTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=25), nullable=True),
    sa.Column('model', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carsTable_brand'), 'carsTable', ['brand'], unique=False)
    op.create_index(op.f('ix_carsTable_model'), 'carsTable', ['model'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carsTable_model'), table_name='carsTable')
    op.drop_index(op.f('ix_carsTable_brand'), table_name='carsTable')
    op.drop_table('carsTable')
    # ### end Alembic commands ###
